# Dependencies
plugins:
  - jekyll-sitemap

# File rules
exclude:
  # default excludes
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # custom excludes
  - Makefile
  - Dangerfile
  - LICENSE
  - README.md
  - assets/
  - package.json
  - yarn.lock
  - scripts/
  - .github/

include:
  - .htaccess
  # bootstrap js
  - node_modules/bootstrap/dist/js/bootstrap.min.js
  - node_modules/bootstrap/dist/js/bootstrap.min.js.map
  # font awesome
  - node_modules/font-awesome/css/font-awesome.min.css
  - node_modules/font-awesome/fonts/FontAwesome.otf
  - node_modules/font-awesome/fonts/fontawesome-webfont.eot
  - node_modules/font-awesome/fonts/fontawesome-webfont.svg
  - node_modules/font-awesome/fonts/fontawesome-webfont.ttf
  - node_modules/font-awesome/fonts/fontawesome-webfont.woff
  - node_modules/font-awesome/fonts/fontawesome-webfont.woff2

keep_files:
  - .well-known

# Site
permalink: /blog/:year/:month/:day/:title/
img_url: /img
excerpt_separator: <!--excerpt-->
sass:
  style: compressed

# Metadata
title: 'Jesse Squires'
description: 'Turing complete with a stack of 0xdeadbeef'
url: https://www.jessesquires.com
logo: /ico/logo.png
timezone: America/Los_Angeles

# Author
author:
  name: 'Jesse Squires'
  twitter: jesse_squires
  avatar: /ico/avatar.jpg

# Data
links:
  github: 'https://github.com/jessesquires/jessesquires.com'
  issue: 'https://github.com/jessesquires/jessesquires.com/issues/new'
  pull: 'https://github.com/jessesquires/jessesquires.com/compare'

social_links:
  twitter: 'https://twitter.com/jesse_squires'
  github: 'https://github.com/jessesquires/'
  stackoverflow: 'https://stackoverflow.com/users/2195632/jessesquires'

feeds:
  rss: '/feed.xml'
  json: '/feed.json'
  applenews: 'https://apple.news/Td_gVU2BDSS2oPbz_sD150w'
