# Dependencies
plugins:
  - jekyll-sitemap

# File rules
exclude:
  # default excludes
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # custom excludes
  - Makefile
  - Dangerfile
  - LICENSE
  - README.md
  - assets/
  - package.json
  - yarn.lock
  - scripts/
  - .github/

include:
  - .htaccess
  # bootstrap js
  - node_modules/bootstrap/dist/js/bootstrap.min.js
  - node_modules/bootstrap/dist/js/bootstrap.min.js.map
  # bootstrap icons
  - node_modules/bootstrap-icons/font/bootstrap-icons.css
  - node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff
  - node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff2

keep_files:
  - .well-known

# Site
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--excerpt-->
sass:
  style: compressed

# Metadata
title: 'Jesse Squires'
description: 'Turing complete with a stack of 0xdeadbeef'
url: 'https://www.jessesquires.com'
logo: /ico/logo.png
favicon: /favicon.ico
timezone: America/Los_Angeles

# Author
author:
  name: 'Jesse Squires'
  twitter: jesse_squires
  avatar: /ico/avatar.jpg

# Data
feeds:
  limit: 30
  rss: '/feed.xml'
  json: '/feed.json'

# URLs
img_url: /img/
blog_url: '/blog/'
categories_url: '/blog/categories/'
tags_url: '/blog/tags/'
stats_url: 'https://stats.jessesquires.com'
